
server:
  port: 8761

spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #make this Eureka server as other Eureka server
    fetch-registry: false  # registry information from another Eureka Server
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
